### ISSUE TITLE
Url helper doesn't work in ViewModel instances when used on the CLI

### ISSUE THREAD

**Issue by blockjon** [zendframework/zf2#3380]
I've had significant trouble today testing some code that tries to use a ViewModel from the CLI. The URL helper just would not work from my .phtml file.

To reproduce, go into your index.php file and comment out the run() function. After that line, try to get a service from the service manager which tries to use the ViewRenderer in order to render a view which uses the URL router such as your "home" route. (My "home" route simply routes to "/")

The behavior I'm seeing is that it works when invoked via a web browser, but it does not work when invoked via CLI.

I discovered this problem when I was writing a unit test. I'm using ZF 2.0.6.

Please advise.

**Comment by weierophinney** [comment]
I've never experienced this, and have written a number of CLI tools that use the URL view helper (including those in PhlyBlog).

My gut is telling me that the problem is likely due to how you're setting up rendering. Normally, in a console application, you will not use the PhpRenderer, but rather the Console renderer. As such, if you're going to use the Url view helper, even with the PhpRenderer, you will need to seed it with a `Zend\Mvc\Router\TreeRouteStack` instance, as the Router service auto-switches between that and the Console router based on whether or not a console env is detected. This will likely require creating a factory for doing so based on the configuration; you can look at `Zend\Mvc\Service\RouterFactory` to see how to accomplish it.
