### ISSUE TITLE
Drop PHP 5.3 support

### ISSUE THREAD

**Issue by Ocramius** [zendframework/zf2#7095]
There, I said it.

Why?

Because it's about time, and composer denies upgrades to versions that aren't supported by our own `composer.json` specification. 

PHP 5.3 is not maintained as of 2014-08-15, and therefore we shouldn't have to deal with it anymore.

Some companies (*hint hint*) still support extra-LTS <=5.3 releases, but that's paid support, and we are not paid to do that.

Off with it's head: thoughts?

**Comment by localheinz** [comment]
👍

**Comment by akrabat** [comment]
+1

**Comment by Ocramius** [comment]
Note: please don't just "+1" here.

I'm more interested in those who say that we should keep support, why, and what they can do for us in order to eventually keep support.

**Comment by asgrim** [comment]
Dropping 5.3 is surely a BC break, shouldn't it wait until ZF3? For me personally I'm happy to move to 5.5 as we use that in production. Would ZF 2.3.* versions still receive updates/security fixes for 5.3 compatibility, and just have 2.4 be 5.5 on?

**Comment by Ocramius** [comment]
@asgrim it would be a BC break if it caused an upgrade to crash a system, but since we use composer to install packages nowadays, you simply cannot upgrade if requirements aren't met.

We still aren't changing API signatures.

**Comment by akrabat** [comment]
We have updated the minimum PHP version number before in both ZF1 and ZF2. This is not unprecedented.

**Comment by philsturgeon** [comment]
Don't drag me into this.

**Comment by gianarb** [comment]
Composer is a good layer to notify this choice without crash of system.
If PHP not support 5.3 why should do it us?

**Comment by grizzm0** [comment]
Is this the like button? :+1:

**Comment by keradus** [comment]
Shouldn't drop of 5.3 version is a BC break and should be targetted 3.x ?

**Comment by Ocramius** [comment]
As exposed earlier, users would be precluded from an upgrade upfront.

**Comment by keradus** [comment]
But still it's a BC break, so if this project follow SEMVER it should be tagged as 3.0, isn't it?

btw, like the idea itself.

**Comment by asgrim** [comment]
I don't seen any other real reason why 5.3 shouldn't be dropped. Would you baseline at 5.4 afterwards? There is only ~8 months left of 5.4 support, so perhaps the minimum version should be 5.5 to give 1y5m left of support?

**Comment by Ocramius** [comment]
It would be a BC break if we broke existing code. Projects bump
dependencies to external libraries (due to new APIs being used and so on)
all the time.

Depending on a higher PHP version seems reasonable to me in this case, as
we'd still maintain 2.2 and 2.3 for users locked in legacy hell.

That said, I realize that I am proposing a change that was never adopted by
any major framework so far.

**Comment by DASPRiD** [comment]
Requiring PHP 5.5 doesn't seem necessary for the moment. With 5.4 we'd already gain traits and the short array syntax, which could both be used to improve ZF's codebase. Existing projects stuck on 5.3 should have no problem with this change, as they are usually already using everything they need from ZF, and would still receive security updates on their specific minor branch.

**Comment by asgrim** [comment]
Surely, the motivation for dropping 5.3 is because it is not supported, then 5.4 will not be supported in 8 months, why not make the leap now? Otherwise (if 5.3 is dropped) this same discussion would happen again in 8 months. I suppose it depends how far you want to go. I don't know about other platforms, but the latest Ubuntu LTS has 5.5, so it's going to be easier to adapt of course than more recent version (5.6 and 7)

**Comment by DASPRiD** [comment]
The question right now is if we'd actually use any of the 5.5 features. If we are not going to do so right now, it'd be pointless to require that version.

**Comment by Ocramius** [comment]
I think it is fair to re-discuss 5.4 when it is EOL also with security
issues

**Comment by keradus** [comment]
> It would be a BC break if we broke existing code.

In fact it is a gateway to it.
If I download a stable 2.3 version for my 5.3 env and want to upgrade - I won't be able to do so.

I am totally for this change, just not at that version - can't it be marked as 3.x?

**Comment by DASPRiD** [comment]
What difference would it make for you, naming wise?

**Comment by keradus** [comment]
As I said, it is a matter of following SEMVER or not.

**Comment by manuakasam** [comment]
As a developer I'd totally go for it. But at the end of the day I do not think that it would do ZF2 any good.

ZF2 is a brand name. Shutting down 5.3 support within ZF2 would make the following statement happen: "ZF2 does not support PHP 5.3". It does not matter if ZF2.3 still works awesome with 5.3 and only ZF2.4+ would break. ZF2 is the brand and that's what we're dealing with here.

If PHP Versions are dropped I would love to see php 5.5 as a minimum due to some incredible use-cases with generators and whatnot. But that would then have to be called ZF3.x.

So as said as it is, but ZF2.x without PHP 5.3 gets a :-1: from me :(

**Comment by carnage** [comment]
It's not a BC break: if you upgrade PHP to the minimum required version all existing code will work without changes.

**Comment by asgrim** [comment]
> Shutting down 5.3 support within ZF2 would make the following statement happen: "ZF2 does not support PHP 5.3"

I think that is a good statement to make ;) it is saying the opposite of what things like WP have done in the past...

**Comment by pauloelr** [comment]
I've been thinking about that and i was relutant to say what i'm going to say now, but i think is time to be said. I think right now the framework is stuck, and that's is mostly because of this kind of discussion, i undertand all the implications of change the major version of the framework, or split it into components (#7072) ou bump the minumim required PHP version to run it, i really do.

But many issues have been opened to deal with all those questions and all of it end up with the same result, more questions, so i think now is time to move foward to somewhere, of course mistakens can happen, and we (the entire community, even those who just use the framework) will be affected if the worng decision be taken, but i think worst of it is to keep stuck on the same place because of being afraid to make those mistakens. IMHO fear is the worst mistaken being made so far.

So doesn't matter if the framework will be called ZF 2.4, ZF 2.5 or ZF 3.0, if the minimum version will be 5.4, 5.5 or even 5.6, if the split happen now or later, there chances of error on all cenarios, errors that will only be discovered after the step being took, so please folks, lets just do something.

That being said, IMHO the minimum version should be 5.5, because we really need to push the community foward, if one major framework doesn't make it the users and host providers will have no reason to do, and we will keep moving in circles eternally.

The framework also need to be splitted as fast as it can be so people can start working on the splited version.

About the framework version number i don't really have an opinion but if change this to 3.0 is imperative to make this changes lets just do that.

**Comment by fabiocarneiro** [comment]
IMO the framework from now on should be versionless. You can use Zend Framework with versioned components.

I agree with what @pauloelr said.

**Comment by Ocramius** [comment]
That is a discussion for #7072, and the framework will keep following semver (for the main package) anyway.

**Comment by texdc** [comment]
:+1: If not `5.5`, then `5.4`.  Traits are just fancy static classes.  Generators are far more beneficial.

**Comment by pauloelr** [comment]
@Ocramius sure about semver but there is no consesus at all about the change on the required PHP version being or not a BC.

IMHO it is NOT because if you change the minimum required version on composer and people running 5.3 try to update it it will just mantain the last stable version avaliable to this specif enviroment since composer do PHP version checks on update.

So we can change the minimum PHP version without fear for code breaking on production software

**Comment by BinaryKitten** [comment]
The biggest issue here is the cognitive dissonance between supported version and the minimum version. These can be 2 massively different things.

I would say that we don't actually need to do anything other than state and change our minimum supported version, I.E. what we will support the continued use of the framework on. 
At present as I see it ZF2 will run on a minimum of PHP 5.3.23 - We also provide support for this level of platform.
If we understand that the code we run should move forward (as with all PHP) then putting out that we will only support running on PHP5.4 (or even PHP5.5) - we don't need to modify anything to prevent it running on earlier versions.

**Comment by philsturgeon** [comment]
Yeah I’ve noticed people getting a tad confused about supported v minimum too.

Supported, just like with internet browsers, means we only run tests against this version and care about bugs on this version.

So, you can very easily drop 5.3 from your unit tests and let people know they can use it if they want, whatever, nothing to do with you. 

“We only support 5.4, 5.5 and 5.6 at this point, but other versions may work. Use at your own risk.”

Done!

**Comment by BinaryKitten** [comment]
@philsturgeon - sorry but I deleted my comment as didn't feel it competently added to the discussion in a way that was clear enough.

**Comment by Ocramius** [comment]
I would avoid that kind of confusion completely. If `composer.json` states `>=5.4` then it is `>=5.4`, no space for interpretation, nor it is required to even boot on `5.3`

**Comment by philsturgeon** [comment]
I'm saying: PHP code may well work on more versions that you specifically put effort into supporting. Like if PHP 5.7 flipped out and you weren't ready for it, that would be an unsupported version.  The composer thing is tricky, as you need to specify a version.   The reason I said anything, was: I discussed it with the new CodeIgniter team, because their docs said 5.2 but their tests were only running against 5.3. I told them they need to say they only support 5.3 and up, even though their code doesn't have anything 5.3 only in it which would break anything. This offered a difference between "minimum unsupported" and "minimum supported."  Just consider there is a difference. You can list something as minimum version 5.4, only supporting 5.4 and up, and it still technically work on 5.3 if you jam it in there somehow.    

---Sent from Boxer | http://getboxer.com

On 6 January 2015 18:17:54 GMT-5, Dariusz Rumiński <notifications@github.com> wrote:@philsturgeon if we have eg code with requirement of 5.4, tests running on 5.4, we support 5.4, we can't just tell "try it on 5.3 on your own risk", and then "yeah, minimum version is 5.3". If 5.3 is compatible then it's supported version, if not the min. ver. is 5.4. At least that is how I look on that matter...  —Reply to this email directly or view it on GitHub.

**Comment by keradus** [comment]
> You can list something as minimum version 5.4, only supporting 5.4 and up, and it still technically work on 5.3 if you jam it in there somehow. 

I can see your point. But the first part of sentence is a promise of support 5.4, when there is no promise about 5.3 and any further changes may cause 5.3 to not work well. That is, `major` change (in the meaning of semver)

**Comment by philsturgeon** [comment]
@keradus I'm not talking about SemVer, but I have witnessed the conversation quietly. 

SemVer, like any piece of text, is open to interpretation. Seeing the various interpreted meanings of what you all think SemVer means is interesting, and is not unlike how people have read various things into multiple religious texts over the ages.

I want to be fairly clear here: **SemVer doesn't give a damn about what version of software you specify as a requirement.**

Just so that's covered. A quick look at the summary:

> 1. MAJOR version when you make incompatible API changes,

Another look at major requirements later on:

> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

"API changes" and "the public API" are both mentioned specifically, and are the important part. Not just any old breaking change, but specifically a breaking change to the API (methods, class names, etc.)

If a project ups the dependency of PHP from 5.3 (which you shouldn't be on anyway) to something like 5.4 (which you should be on) then nothing in the API has changed, therefore SemVer remains about as interested as the Honeybadger. 

I have argued in the past that Laravel should leave its PHP version change to a major version, but only because they should really consider implementing functionality of that version at the same time, which would involve breaking the public API, and therefore SemVer starts to care.

If you change the PHP version requirement, without changing the public API, then Zend does not need to bump to a major version.

Thems just the facts. :sunglasses:

**Comment by keradus** [comment]
> 5.3 (which you shouldn't be on anyway)

I am for leaving 5.3 (https://github.com/zendframework/zf2/issues/7095#issuecomment-68865142).
On my personal/commerce projects I use 5.5+, but as one mentioned one could have not have opportunity to migrate his legacy code (https://github.com/zendframework/zf2/issues/7095#issuecomment-68871056).


In fact, you gave intresting argument. Just, for me, method API is not only input + output, but also dependencies. If they are compatible then great, here, IMO, switching PHP version may produce incompatibility in dependencies - the language features itself. (Little less controversial example - if you don't change input and output, but start throwing totally new, not built-in exceptions, is this an interface change or not? For *me* it is.)


I think we are talking same arguments over and over again.
I will be extra happy to drop 5.3 and go even to 5.5. Then I just be a little happy for seeing it on 3.x line, not 2.x.

**Comment by philsturgeon** [comment]
I’m not particularly interested in which versions people use personally, I was just explaining that the choice of PHP versions and SemVer have literally no relation to each other.

So long as the public API is not changed in a BC-breaking fashion - which so far is not being discussed or suggested - then there is no need to worry about or making ZF 3 for the sake of some misplaced understanding of SemVer’s requirements.

If somebody wants to say “Well it might be a good idea to bump it to 3.0 because FOO” then fine, but FOO cannot be “SemVer.”

Anyway, carry on folks. :)

**Comment by keradus** [comment]
Let say our library use Foo library at version 2.x. It was changed, some major changes, bumped into 3.x. We update deps and use 3.x version now. Is this a major change for our project or not? Should ve bump our major or not?

And then, somene use in his project our library and some other Zoo library. Yesterday our library uses Foo 2.x and Zoo library uses Foo 2.x. Everything is fine. Today our library uses 3.x, but we didn't care and just bump minor, not major version. Someone want to update his deps and sorry, he can't. And that sucks with updating deps into next major version and bump only minor one in our project.

**Comment by philsturgeon** [comment]
If you look at what SemVer says, then the answer is still no. You are reading things that aren’t there and summoning complex use cases that are not relevant. :)

If the Zoo library is specified only as a dependency of Foo, then it is an internal change and nobody cares. 

If the Zoo library is also specified as a dependency of the application, then that user will have to hold off on using a new version of Foo and Composer will let them know about that.

This is fundamentally how dependency management works and its all fine, and SemVer still does not care about the minimum PHP version.

**Comment by asgrim** [comment]
In light of what's been said, I would propose setting Composer min version
to 5.4. Reason being - that would be min supported, so out the box that is
what it would install. If you really wanted to shoehorn into 5.3 then you
can do so by kludging things so it gets installed, but that would be on
your own head.

**Comment by philsturgeon** [comment]
That’s what I was getting at. :)

**Comment by weierophinney** [comment]
Cherry-picking two quotes:

> Dropping 5.3 is surely a BC break, shouldn't it wait until ZF3?

and:

> companies are still running 5.3 and upgrades of old systems are not always even possible.

One argument not really made, but which should be: If you're using PHP 5.3 currently, likely you have very stringent requirements around dependency changes anyways, and _will not be able to upgrade your ZF version either_. In which case, the argument around whether or not a bump in PHP version for ZF is a BC break is completely moot -- you're not upgrading anyways.

For those of you not following the latest PHP blogs and news, I think @Ocramius probably should have pointed out the [blog post by Anthony Ferrara which likely prompted this issue](http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html). He points out that keeping a 5.3 requirement is likely a bad idea for reasons of:

- Security. 5.3 is no longer getting security updates. Sure, some vendors are backporting security patches, but we have no idea what percentage of our users fall into this category. As such, maintaining 5.3 support on the part of the project is promoting insecure PHP versions for our users.
- Interoperability. The longer we support 5.3, the longer we're either holding back the PHP ecosystem from adopting new language features, or our own users from using code from the larger ecosystem (as the PHP version now becomes a limiting factor).

I think the security point alone is reasonable rationale. We bumped from 5.3.3 to 5.3.23 due to a combination of security and maintenance issues (buggy behavior in the PHP engine itself was making some fixes on our part impossible). Why shouldn't we bump to a more secure version of PHP in order to protect our users?

I also want to point out this comment:

> Supported, just like with internet browsers, means we only run tests against this version and care about bugs on this version.
> 
> So, you can very easily drop 5.3 from your unit tests and let people know they can use it if they want, whatever, nothing to do with you.

Well, yes and no. I recently was bit by something like this -- a developer had neglected to specify a minimum PHP version in their Composer file, and another project I was working on was depending on it. When I tried to specify a PHP 5.3 minimum version in my project, and then ran tests, I discovered that the dependency was using version-specific features that caused my code to fail (in this case, short-array notation). I think we need to be explicit about supported versions -- it's not just a case of removing them from the unit tests, but letting consumers know what they actually need in order to use the code.

My main point is: if we adopt a minimum version, we're also messaging to our contributors that they can use features from that version when submitting patches -- and those language features may not be compatible with older versions. As such, we _must_ be explicit about what we support.

I do agree with @philsturgeon with regards to whether or not SemVer and bumping dependency requirements are related -- they're not. SemVer is about the project's API; how it accomplishes that is not related. I'd argue that if I need to add a dependency or bump a dependency version, I should tag a new version -- but it _definitely_ doesn't need to be a new major version; the only reason for the new version is to indicate a change was made.

With regards to what version to pin to: I think we could safely move to 5.4 for ZF 2.4. We're planning a 2.5 within a few months of 2.4, and can revisit minimum version again then, and if/when we are ready to consider 3.0, we can revisit yet again. But 5.4 seems like the minimum needed to ensure users are on secure versions, and to reduce the maintenance overhead for contributors.

I'm relaying this back to my cohort at Zend, and hopefully we can have a decision quickly.

**Comment by bartmcleod** [comment]
+1 for 5.4 in ZF2.4
-Bart

Verstuurd vanaf mijn iPhone

**Comment by philsturgeon** [comment]
> Well, yes and no. I recently was bit by something like this -- a developer had neglected to specify a minimum PHP version in their Composer file, and another project I was working on was depending on it. When I tried to specify a PHP 5.3 minimum version in my project, and then ran tests, I discovered that the dependency was using version-specific features that caused my code to fail (in this case, short-array notation). I think we need to be explicit about supported versions -- it's not just a case of removing them from the unit tests, but letting consumers know what they actually need in order to use the code.

Yep, I wasn't talking about Composer's minimum version - that needs to be the same as your minimum supported version. So many things.

1. The minimum version of PHP your code will actually run on. Maybe thats 5.3.
2. The minimum version of PHP you specify in Composer.
3. The minimum version of PHP you support, listed in your docs and user facing stuff everywhere.
4. The minimum version of PHP you test against.

2, 3 and 4 always need to be the same, or you're gonna have a bad time. 

I wasn't really talking about Composer when I first jumped in. :)

**Comment by philsturgeon** [comment]
Basically what @asgrim said.

**Comment by GeeH** [comment]
POINT: The original poster asked to bump to 5.4 because its a currently supported version of PHP and nothing to do with newer features it gives us, I think that any discussion related to features that would be cool to use are not appropriate in this thread.

OPINION: Supporting PHP 5.3 implies that we care more about potential user base than we do about our user's security, and I would strongly suggest we bump to 5.4. Given the small amount of friction here (nobody of any note is against it :P) then it's entirely conceivable we can bump again once 5.4 reaches EOL. Personally I don't feel that it is necessary to bump to 5.5 now just so we don't have to bump again in the future. With that argument we should bump to 5.6.

ASIDE: Anyone who is paying Zend to support 5.3.x with backported security fixes is almost certainly not running a ZF2 site or they would have no reason to not be running 5.latest, so I think that point is moot here.

:+1:

**Comment by GeeH** [comment]
If we do bump to 5.4, then we should absolutely accept PR that use 5.4 versions and not soft-limit to 5.3.x just so we can say "it will work but we won't support it".

**Comment by stefanotorresi** [comment]
Honestly, as soon as the minimum requirement will be bumped, we would surely have backward incompatible PRs (e.g.  #5480 just the first to tip out of my head) and there is a reason why these are marked `[ZF3]`: because they're backward incompatible.
If it's not about the features but about the security, that would imply that the code should be kept compatible with 5.3, and good luck attempting that (even installation without composer is close to be unsupported!).

Personally, I'm not against the bump at all, on the contrary, but we must admit it is *de facto* a huge backward incompatible change; so go ahead, but the implications should be disclosed **very** carefully.

Honestly, forgive the digression, but I would like much more taking some steps to make ZF3 a concrete work in progress, a lot of work was been done about a year ago that suddenly came to a stop and is well worth picking up again. I'd rather have a ZF3 pre-alpha1 in 2 months with php 5.5 requirement and a bunch of opened [zf3] PRs merged, than a 2.4 with the bumped requirement.

The 5.4 bump on the 2.x branch could be done in a late minor like it was done for ZF1, for security implications but without much BC breakage (because at that point new features would be targeted at the 3.x branch).

**Comment by Ocramius** [comment]
> we would surely have backward incompatible PRs

Anything that breaks semver versioning gets delayed until after 2.5.

 > that would imply that the code should be kept compatible with 5.3

Code will not be kept 5.3 compatible. Security issues will consider that people installed at least PHP 5.4, we won't polyfill security issues in PHP itself for people.

 >  I'd rather have a ZF3 pre-alpha1 in 2 months

See #7072 about that

 > The 5.4 bump on the 2.x branch could be done in a late minor like it was done for ZF1, for security implications but without much BC breakage (because at that point new features would be targeted at the 3.x branch).

Again, let me clarify, security issues will be fixed in 2.x in any case, regardless of which PHP version is supported, as long as the security issue is caused by zendframework itself. Dropping PHP 5.3 support doesn't mean that we drop security support on versions earlier than the one that caused the requirements bump.

**Comment by Ocramius** [comment]
This is settled and it is going to happen.

Please see #7119 and eventually PR against that branch, if you have anything that needs to be cleaned up after PHP 5.3 support drop.

**Comment by padraic** [comment]
Changes in dependency versions are not an issue for semver, I'm surprised it's even being mentioned. PHP 5.3 is dead. It doth not existeth any longereth. If you are using PHP 5.3, the canonical 5.3, then you are a sitting duck for blackhats. There are precisely zero, I say again, ZERO, reasons to maintain a minimum dependency on a dead insecure version of anything.

All arguments to the contrary are contributing to the fallacy that money, time, or whatever is a sufficient excuse to persist insecure PHP versions. That is not an excuse. If you can build it, then you can stump up for the very obvious, very predictable and very inevitable event of a PHP version going EOL.

**Comment by asgrim** [comment]
Woo \o/

**Comment by Thinkscape** [comment]
@weierophinney 

> I'm relaying this back to my cohort at Zend, and hopefully we can have a decision quickly.

What was the response ?

**Comment by Thinkscape** [comment]
@padraic I'd say it's not about compatibility but more about usability. It's easier to remember for humans that `2.4 => php 5.4` and maybe `2.5 => php 5.5`. Not required, but welcomed.

Hmmm... also this: https://github.com/cakephp/cakephp/issues/5602#issuecomment-69674017

**Comment by weierophinney** [comment]
We'll be supporting PHP 5.3 for ZF 2.4 -- which we will mark as a Long Term Support release; this way, developers who _must_ stay on 5.3 know they have a supported version until they can upgrade.

After 2.4 is released, we will start supporting PHP 5.5 as the minimum required PHP version.

**Comment by carnage** [comment]
Can't we mark 2.3 as LTS and move forward with 2.4 on 5.4?
