### ISSUE TITLE
Cache-specific Travis setup is problematic

### ISSUE THREAD

**Issue by weierophinney** [zendframework/zf2#7271]
This is really targeted at @marc-mabe 

I recently merged #7067 which enables more tests on Travis for the various Cache backends, including APCu, Redis, and memcached.

What I'm noticing:

- Longer build times. Building the apcu extension takes some time. In fact, sometimes it fails (see https://travis-ci.org/zendframework/zf2/jobs/52332057 as an example).
- It doesn't work across builds, leading to increasing amounts of env-specific logic (see https://github.com/zendframework/zf2/blob/a011465532db36554bbc06f0cb26174ccc120c93/.travis.yml#L13-L17)

While I would like to enable this, unfortunately, it's hampering our ability to get useful build feedback. As such, my plan is to disable these features; we can discuss adding them back after the cache component is isolated in its own repo (i.e., post 2.4).

**Comment by marc-mabe** [comment]
@weierophinney:

> Longer build times. Building the apcu extension takes some time. In fact, sometimes it fails (see https://travis-ci.org/zendframework/zf2/jobs/52332057 as an example).

On the example you given the build hangs on "Enable full APC compatibility [yes] : " because of the changes in https://github.com/weierophinney/zf2/commit/a73c6cfd9ba779ca541c688a5323273fa0f5cbd8 -> missing to pipe a new line (`echo ""`) to `pecl install apcu-beta` to answer the question with the pre-selected value.

But sure in cases of the apcu extension it needs some to to compile but in this special case I personally think it is ok because of the popularity of this extension.

For the redis and memcache extension the time impact should be ignorable as it only needs to be enabled.

The environment specific logic is only because of differences in the environments be have to support but extensions are different. So I think we should test it.

PS: It looks like there is some logic added to enable PHP7 nightly builds and is mostly related to the fact that not all extensions are working for PHP7 for now.

**Comment by Maks3w** [comment]
This has been fixed and improved on zend-cache repo.
