### ISSUE TITLE
session_regenerate_id

### ISSUE THREAD

**Issue by fsvxavier** [zendframework/zf2#7317]
<b>Warning</b>:  session_regenerate_id(): Cannot regenerate session id - headers already sent in <b>C:\server\www\mkmanager\vendor\zendframework\zendframework\library\Zend\Session\SessionManager.php</b> on line <b>272</b><br />
<br />
<b>Warning</b>:  session_regenerate_id(): Cannot regenerate session id - headers already sent in <b>C:\server\www\mkmanager\vendor\zendframework\zendframework\library\Zend\Session\SessionManager.php</b> on line <b>272</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>C:\server\www\mkmanager\vendor\fsvxavier\cityware\library\Cityware\Mvc\Controller\AbstractActionController.php</b> on line <b>72</b><br />

I using php 5.6, nginx and ZF2.3.5

**Comment by Bittarman** [comment]
This appears to be very incomplete, and possibly expected behaviour. you already sent output to the browser in C:\server\www\mkmanager\vendor\fsvxavier\cityware\library\Cityware\Mvc\Controller\AbstractActionController.php on line 72, which makes it impossible for php to send headers.

I'm going to close this for now, but please feel free to re-open with more complete information about what you did and why you feel this is a bug in ZF.
