### ISSUE TITLE
$HTTP_RAW_POST_DATA

### ISSUE THREAD

**Issue by fsvxavier** [zendframework/zf2#7318]
Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

I using php 5.6, nginx and ZF2.3.5

Zend\Feed\PubSubHubbub using

```php
/**
 * Return the raw body of the request
 *
 * @return string|false Raw body, or false if not present
 */
protected function _getRawBody()
{
    $body = file_get_contents('php://input');
    if (strlen(trim($body)) == 0 && isset($GLOBALS['HTTP_RAW_POST_DATA'])) {
        $body = $GLOBALS['HTTP_RAW_POST_DATA'];
    }
    if (strlen(trim($body)) > 0) {
        return $body;
    }
    return false;
}
```

and generating error in Ajax request.

**Comment by weierophinney** [comment]
If you look at the conditional, we're accessing `HTTP_RAW_POST_DATA` only if reading `php://input` returns an empty string. The reason for this is because, prior to PHP 5.6, `php://input` was read-once. This means that if another process, such as the MVC request instance, accessed the request body previously, no other process can access it. (The MVC request instance caches the contents for this very reason.)

Essentially, the code in that method is a fail-safe, as `HTTP_RAW_POST_DATA` is always populated, and thus guaranteed to be present. Until we make 5.6 our minimum version, this is a necessary precaution.
