### ISSUE TITLE
[Filter/OpenSSL] Passphrase needs to be set at initialisation

### ISSUE THREAD

**Issue by barryvdh** [zendframework/zf2#7322]
Following this example from the docs: http://framework.zend.com/manual/current/en/modules/zend.filter.set.html#encryption-with-openssl

> When you want to encode also the keys, then you have to provide a passphrase with the setPassphrase() method. When you want to decode content which was encoded with a passphrase you will not only need the public key, but also the passphrase to decode the encrypted key.

    // Use openssl and provide a private key
    $filter = new Zend\Filter\Encrypt(array(
       'adapter' => 'openssl',
       'private' => '/path/to/mykey/private.pem'
    ));

    // of course you can also give the public keys at initiation
    $filter->setPublicKey(array(
       '/public/key/path/first.pem',
       '/public/key/path/second.pem'
    ));
    $filter->setPassphrase('mypassphrase');

When I use a private key which requires a passphrase, the construct will fail on an invalid key exception, so it never reaches the `$filter->setPassphrase('mypassphrase');`

This is because the `__construct()` calls `_setKeys()` which reads/checks the keys directly, before the passphrase is set. See https://github.com/zendframework/zf2/blob/a1aae5fdd27a422beb32c56ddf5a197654a0f94a/library/Zend/Filter/Encrypt/Openssl.php#L100-L154

The solution is simple, use the `passphrase` key in the `$options` config directly. But I'm not sure if this is expected behavior.

So options:
1. Update the docs to something like:

    $filter = new Zend\Filter\Encrypt(array(
       'adapter' => 'openssl',
       'private' => '/path/to/mykey/private.pem',
       'passphrase' => 'mypassphrase',
    ));

2. Parse the keys when needed, not on the constructor directly?

I'm willing to fix the docs issue if needed. I'm not sure if I'm the best person to update the code though ;)

**Comment by ezimuel** [comment]
@barryvdh you right, the `setPassphrase()` cannot be executed after the `__construct()`. I was surprised by this behaviour, because it was not covered in the unit tests. I spent some times and I found that the unit test was using a private key without passphrase :(
I sent the PR #7362 to use a valid private key + passphrase. I think we need to fix only the documentation in the manual, the **passphrase** must be passed in the constructor of the class.
Can you send a PR against https://github.com/zendframework/zf2-documentation ? Thanks!

**Comment by ezimuel** [comment]
@barryvdh Because I fixed the documentation for PR #7323 I fixed also the docs for this PR at the same time. Thanks again for reporting this!
