### ISSUE TITLE
2.4.1/2.3.8 Zend Components are not on Packagist

### ISSUE THREAD

**Issue by smazurov** [zendframework/zf2#7516]
Given the security advisory issued on May 7th, its strange to see that packagist still does not have 2.3.8 or 2.4.1 available, can that be fixed so we can upgrade, please?

**Comment by waltertamboer** [comment]
I agree. How many releases are still planned until all components have their own repository? I'd like to suggest that until that is done, all packages are updated on the same day as a new release is done. Should be part of the default release procedure.

**Comment by gianarb** [comment]
Hi! I see them here
https://packagist.org/packages/zendframework/zendframework

**Comment by Ocramius** [comment]
@GianArb the manual split didn't run yet

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by gianarb** [comment]
ahh yes :) Sorry :) I seen it after my comment

**Comment by eXtreme** [comment]
still no tags for zend-http and zend-mail which cause sensio security checker report vulnerable dependencies in my project

**Comment by Ocramius** [comment]
Please rely on the main zendframework/zendframework package until somebody
in the CR team got to actually do the split.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by smazurov** [comment]
> Please rely on the main zendframework/zendframework package until somebody in the CR team got to actually do the split.

This is not a solution.

I don't understand.  Somehow these packages existed before, they are supported by Zend, they are linked in the official download page, yet they continue to be vulnerable to a published security advisory. What happened between **2.4.0** and **2.4.2** that prevents you from releasing the packages? 

I read zendframework/component-split#6 and the gist, but I imagine this is a new development and whatever way you had before should continue working, no?

**Comment by Ocramius** [comment]
Yes, tho I simply don't have a reliable connection to work on the split
myself atm.
@weierophinney or @Maks3w can attempt it if/when they have time.

 > they are supported by Zend

Zend doesn't really support anything here, afaik: this is a community
project sponsored by Zend, not supported as a product.
We should be thankful for the help they give us, but it is not a product.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by johnnye** [comment]
It would be really helpful if these could make their way onto packagist asap for those of us that use just one or two components.

**Comment by weierophinney** [comment]
> I don't understand. Somehow these packages existed before, they are supported by Zend, they are linked in the official download page, yet they continue to be vulnerable to a published security advisory. What happened between 2.4.0 and 2.4.2 that prevents you from releasing the packages?

There are a number of issues blocking this:

- First, the "solution" we have currently for the components is a manual one, and error-prone. We have tried to automate the splits a number of times, but every solution we've tried has introduced errors into individual components, leaving them unusable. The current solution is one we manually trigger, and then we verify the results before pushing. It takes at least half a day *if it works correctly* to accomplish.
- To solve this, and also to achieve other goals, we announced with 2.4.1 that we are splitting the components into their own repositories for ongoing development (vs. development in the main ZF2 repository). That effort has been in progress since before 2.4 was released, and we'd hoped to get everything split out the day immediately following the release. Unfortunately, we ran into a number of problems, and only yesterday finally formulated a reliable script. We are literally right now in-process, and running our lasts tests. At which point…
- we can trigger parallel runs splitting out all components. But this process takes between 6 and 12 hours, depending on the combination of git version, whether you're on a ramdisk or an HDD, etc. And after those run, we have to verify that the history, commits, and tags are correct.

Things are looking good at this point, and we should have the components completed tomorrow. However, as noted, _we are still running last tests_, and last week, everything looked fine until the components started updating. As such, we're being very cautious.

It does not make sense for us to trigger the old manual process, considering we're closing in on completing the split. As such, I urge patience; we'll have tagged components shortly. You can use the full ZF2 library until then if your needs are urgent.

**Comment by weierophinney** [comment]
Component split is complete, and all packages are tagged for all versions.

**Comment by Martin-P** [comment]
Just for clarity (and my personal curiousity): the release process has been updated according to the provided feedback to prevent this from happening again?

**Comment by grizzm0** [comment]
@Martin-P Please read [this article](https://mwop.net/blog/2015-05-15-splitting-components-with-git.html) about the future of the components development process.

**Comment by Martin-P** [comment]
@grizzm0 Thanks, I know about the split for a long time, but that was not my question. My question was about the release procedure *untill* the split. As long as there is no split, the situation as described in this issue can happen again and to prevent that I think release procedure needs to be updated. My question is: has this release process been updated accordingly?

Furthermore the split is for ZF3, so not (yet) relevant for ZF 2.4:
> Today we accomplished one of the major goals towards Zend Framework 3: splitting the various components into their own repositories.

**Comment by gianarb** [comment]
@Martin-P I don't remember where I seen this information but the split in components is the only feature for ZF 2.5.0..

**Comment by Martin-P** [comment]
@gianarb Please don't only read the last response, but also the context of my response :wink: 
See: https://github.com/zendframework/zf2/issues/7516#issuecomment-102602034 (the link where you read the information is in that comment).

But perhaps we can get back to the issue and my question?
