### ISSUE TITLE
Session Compatibility 3rd party libraries

### ISSUE THREAD

**Issue by tdzierza** [zendframework/zf2#7523]
I tried to integrate File Manager (KCFinder) with my zf2 application, but session not working.

According to documentation this is my part of code inside KCFinder source file (just before session_start())

if (!session_id()) {

            if (isset($_CONFIG['_sessionLifetime']))
                ini_set('session.gc_maxlifetime', $_CONFIG['_sessionLifetime'] * 60);
            if (isset($_CONFIG['_sessionDir']))
                ini_set('session.save_path', $_CONFIG['_sessionDir']);
            if (isset($_CONFIG['_sessionDomain']))
                ini_set('session.cookie_domain', $_CONFIG['_sessionDomain']);

	    $cwd = getcwd();
	    chdir('/path/to/my/ZF2APP');
	    require 'init_autoloader.php';
	    \Zend\Mvc\Application::init(require 'config/application.config.php');
	    chdir($cwd);
	    session_start();

        }
I awlays get Notice: A session had already been started - ignoring session_start()

It's looks like connflict with SessionManager ... So is it possible to work together with 3rd part app ? because there are many different opinion in internet.

**Comment by Martin-P** [comment]
> According to documentation this is my part of code inside KCFinder source file (just before session_start())

That probably works for regular PHP code, but you are using a framework now and you have to adapt your code accordingly.

> I awlays get Notice: A session had already been started - ignoring session_start()

In that case ZF2 has already started a session and you should use the ZF2 way for sessions and not `session_start()`.

> It's looks like connflict with SessionManager ... So is it possible to work together with 3rd part app ? because there are many different opinion in internet.

In most cases you write your own ZF2 module which creates a bridge between the PHP-code (in this case KCFinder) and ZF2. It seems someone has already done that, because the [first hit on Google](https://www.google.nl/search?q=kcfinder+zf2) mentions this GitHub repository: [raykolbe/KCFinder](https://github.com/raykolbe/KCFinder).

**Comment by tdzierza** [comment]
According to documentation - I mean http://framework.zend.com/manual/current/en/modules/zend.session.manager.html

About using session_start in 3rd part app you can read here: https://github.com/zendframework/zf2/issues/3880#issuecomment-14160074 and in documentation.

Maybe raykolbe/KCFinder worked 4 years ago. But now we have Zend 2.4 and totaly different version of kcfinder. So this is deprecated.
But out of curiosity i checked it. Firstly it requires zend 2.1, but as we can read in issue 3880 (by samsonasik he mentioned that session_start just worked in older versions.
So I used from raykolbe/KCFinder only integration file zf2.php, but it nothing change ...
https://github.com/raykolbe/KCFinder/blob/master/integration/zf2.php

**Comment by Martin-P** [comment]
It is possible the documentation of [Session Compatibility](http://framework.zend.com/manual/current/en/modules/zend.session.manager.html#session-compatibility) is out of date. If a session has already started you can just remove `session_start()` or check if a session has already started before using `session_start()`. For debugging you can use `var_dump()` to check the contents of `$_SESSION`.

If `raykolbe/KCFinder` is deprecated you have to create your own bridge to make it work. You can use `raykolbe/KCFinder` as inspiration for that.

**Comment by Martin-P** [comment]
Tested the code of [Session Compatibility](http://framework.zend.com/manual/current/en/modules/zend.session.manager.html#session-compatibility) with ZF2.4.2 and you *can* get the notice `A session had already been started - ignoring session_start()`. This only happens if you initiate a session in ZF2. So it depends on your application if you need `session_start()` in your code.

Tested ZF2 and used costom session variables and it works fine for me.

**Comment by tdzierza** [comment]
I made my own integration file for kcfinder. It contain code from Session Compatibility, but without session_start(). Thanks to that it's working without warnings and i have access to whole $_SESSION data from zf2 inside kcfinder.
