### ISSUE TITLE
[ZF3] Zend Storage component

### ISSUE THREAD

**Issue by YP28** [zendframework/zf2#7599]
I'm not sure if ZF3 changes are still open for discussion, but something that has been bothering me for a while now that there's not single component to define storage. 

Is this something that just grew that way because different components needed different kinds of storage, or is this a well made decision? 

Please share some thoughts on this, and the option of creating a component specifically for storage.

**Comment by Ocramius** [comment]
Please define what you intend for storage :-\

**Comment by YP28** [comment]
Components like Zend-Cache, Zend-Authentication and Zend-Session all use a kind of storage. It just seems weird that they all have different implementations of the storage they need instead of one uniform way of describing storage which can be used in all components.

**Comment by YP28** [comment]
Besides that, the storage component could be used to store things in key value databases, because in my opinion they are not just to use for caching.

I might be completely wrong on this, just expressing my thoughts.

**Comment by Ocramius** [comment]
I (personally, really just personally), don't see a point in ZF implementing persistence logic.

I don't want to turn you down directly on this, but I also work on doctrine project, which is *only* about persistence stuff, heh...

**Comment by stevleibelt** [comment]
@YP28 I get your point. [Zend-Authentication](https://github.com/zendframework/zend-authentication), [Zend-Cache](https://github.com/zendframework/zend-cache) and [Zend-Session](https://github.com/zendframework/zend-session) are implementing a storage interface ([auth](https://github.com/zendframework/zend-authentication/blob/master/src/Storage/StorageInterface.php), [cache](https://github.com/zendframework/zend-cache/blob/master/src/Storage/StorageInterface.php) and [cache](https://github.com/zendframework/zend-session/blob/master/src/Storage/StorageInterface.php)).

Right now, they are looking quite differently. The only approach to align them would be to use the basic [crud syntax](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete).
I tried to create an [unified storage interface](https://github.com/bazzline/php_component_database_file_storage/blob/master/source/Net/Bazzline/Component/Database/FileStorage/RepositoryInterface.php) on my own, but this is really hard to define.

Maybe you can write a draft for it @YP28?

@Ocramius you are right, if this approach would be to unify this three components (and maybe get an PSR out of it *dreaming*), then the interface must be as generic and as basic as possible.
The real work should be covered by big orms like propel or doctrine.

Enjoy your day

**Comment by YP28** [comment]
Thanks for your reply @stevleibelt. 

They indeed look quite differently, but they all use some kind of key-value store. So I think there should be a basic implementation for a storage interface based on CRUD. 

Now you mention it, it might be better implemented as a PSR standard than implemented here in Zend Framework.

**Comment by stevleibelt** [comment]
@YP28 

PSR would be the goal. Maybe you can add a request there and link to this thread.
Otherwise, a framework as "playground to see if things are working well" is a good base to evolve a PSR out of it.

**Comment by YP28** [comment]
@stevleibelt 

I've made a first draft of a PSR standard. Would you mind giving some feedback on it?
https://github.com/YP28/fig-standards/tree/psr-storage/proposed/psr-storage

**Comment by stevleibelt** [comment]
@YP28 
,

thanks for your work already. And also thanks I can spend my two cents on your idea.

Before the feedback, I have to tell you a bit about myself and how I try to create software and interfaces in this case.
I try to follow the KISS principal and I want to create interfaces, where I don't have to think about it. The method names should not allow a big room for interpretations. Thats why I also don't like to put that much logic into one method, one method to do one thing.

"As you wished", here is my feedback :-). I have to do it here, since I can't open an "Issue" on your forked project page.

I like the "string or an object implementing the __toString() method".
I don't like the idea with the "options". I know it is an generic approach but things like TTL is something I would like to separate from the Interface. To deal with the TTL problem you mention, I would prefere implementing a "setTTLTo($seconds)" method in the storage.

As mentioned above it is hard for me to only have four methods.
I don't like the idea to do a check like "if ($return instanceof StorageCollection) { //deal with collection of data sets } else if ($return !== null) { //deal with single data set } else { //deal with no returned data set }" since I have to do this each time call one of the fitting methods.
Because of that, I would like to have the following list of methods defined:
```php
interface StorageInterface
{
    /**
     * @param scalar|array $value
     * @param string $key
	 * @return string
	 * @throws StorageException
	 */
    public function createOne($value, $key = null);	//or maybe "create"?

	/**
	 * @return null|mixed
	 * @throws StorageException
	 */
	public function readOne();

	/**
	 * @param int $length
	 * @param int $start
	 * @return null|array
	 * @throws StorageException
	 */
	public function readMany($lenght, $start = null);

	/**
	 * @return null|array
	 * @throws StorageException
	 */
	public function readAll();

	/**
	 * @param scalar|array $value
	 * @return null
	 * @throws StorageException
     */
	public function updateOne($value);

	/**
	 * @param scalar|array $value
	 * @param int $length
	 * @param int|string $start - either an index or a key
	 * @return null
	 * @throws StorageException
     */
	public function updateMany($value, $length, $start = null);

	/**
	 * @param scalar|array $value
	 * @return null
	 * @throws StorageException
     */
	public function updateAll($value);

	/**
	 * @return null
	 * @throws StorageException
	 */
	public function deleteOne();

	/**
	 * @param int $length
	 * @param int|string $start - either an index or a key
	 * @return null
	 * @throws StorageException
	 */
	public function deleteMany($length, $start = null);

	/**
	 * @return null
	 * @throws StorageException
	 */
	public function deleteAll();

	/**
	 * @param string $key
	 * @return $this
	 */
	public function filterByKey($key);

	/**
	 * @param string $value
         * @param bool $usefilterAsOrInsteadOfAnd
	 * @return $this
	 */
	public function filterByValue($value, $usefilterAsOrInsteadOfAnd = false);	//maybe this would add to much complexity
}
```

As you can see, I try to avoid adding the parameter "$key" everywhere. Adding it to the "create" method make sense for me, since even I already don't like to write "->filterByKey('foo')->create($data);".
I like the idea that signals "hey man, the interface is not responsible for creating the keys". But we need to make the key optional when we think about databases with auto incrementing keys.

The exceptions are always thrown if an action could not be execuded, like deletion for example ("table lock" to speak in database terms again).

There are still open questions in my mind. One I can easily put into words is this one: "should this standard define a [collection](https://github.com/schmittjoh/php-collection) also?".

I know my aproach is more heavier than yours. Thats why I would like to have your feedback too :-).

**Comment by YP28** [comment]
Moved to https://github.com/YP28/fig-standards/pull/1
