### ISSUE TITLE
peformance but  an issue 

### ISSUE THREAD

**Issue by faghihian71** [zendframework/zf2#7633]
hi i do every thing using class map template map doctrine memchach use module cache and every thing but still a simple page without database connection with ab -k -n 1000 -c 100 test.com shows response time near 2000 why ?  why zf2 is too heavy please give me a way to speed up i lanuch my website and i am so sad for choosing this framework its 4x slower than zf1 why ? i searched web for 3 days i open all of google links and do their works for zf2 speed up but still high cpu usage and slow response

**Comment by mwillbanks** [comment]
ZF3 is in progress with massive increases.  Each specific application is different and can have different potential bottlenecks.  If you are not going to supply details or cachegrind output then we cannot help you further.  Thank you for doing your research on the active gains that we have been making in ZF3 we look forward to your future issues that supply no detail and for which you have not done your research.

**Comment by tasmaniski** [comment]
@faghihian71  this video is awesome, take a look https://www.youtube.com/watch?v=QwpGPlL8oZc 

time of 2000 is too large, my req. of ZF2 app is only 20ms maximum... so you have to benchmark it to find bottlenecks...

**Comment by weierophinney** [comment]
@tasmaniski —

What are you running  your benchmarks on, in terms of hardware? Is it your desktop? a virtual machine? AWS EC2? Benchmarks will vary a ton based on where you run them and where the server is that you're running them against.

Additionally, you're running with a concurrency of 100; this is emulating very heavy traffic, which you would need to a use a variety of strategies for:

- static caching of pages
- HTTP caching
- configuration caching
- opcode caching
- and strategies such as proposed in EdpSuperluminal, which compiles all classfiles in your application to a single file

I have consistently had < 50ms response times from Apigility applications (Apigility runs on top of ZF2), even under load by layering caching strategies such as the above.

In order to find out where to cache, you need to use a dedicated profiler. Benchmarking only takes you so far; you need some idea of where the application is spending its time, not just the overall time it takes. That's why @mwillbanks suggested cachegrind output. You can also use tools such as XHProf or Zend Server/Z-Ray to do such profiling. These tools show you where the application is spending its time, and you can use that information to improve your performance strategies.

(This is what we've done with the event manager and service manager, allowing us to speed them up *considerably* for their upcoming v3 versions.)

**Comment by weierophinney** [comment]
Sorry, last was actually directed at @faghihian71  —sorry, @tasmaniski !

**Comment by tasmaniski** [comment]
Ok, no prob :)

**Comment by faghihian71** [comment]
@weierophinney hi and thank you for your response ,
my total memory is 4gb 
my cpu is : Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz 2 core of it (i have vps of server)
nginx,php-fpm

enabled opcache on php ,
enabled memchache for doctrine ,
module chaching ,


i get benchmark with this so 
after i speaking i heard that i should profiling ,so now i am go to tutorials to find out how profiling,thank you for your response i go for cachegrind and profiling 
 but i have question i put die ('hello world') on bootstrap function on application module in that page i havent any db connection or controller or .... so why i have high load yet ? i use classmap autoloader template map autoloader composer dump-autoload -o (for optimizing) .

**Comment by faghihian71** [comment]
@tasmaniski thank you for your good link

**Comment by faghihian71** [comment]
@mwillbanks thank you for your helping

**Comment by mwillbanks** [comment]
@faghihian71 there is so much that can be causing the load.  if you are almost out of memory or even if 1 process is not tuned and you are near a memory limit and start to swap.  All of these things can cause major changes.  Server tuning is an art and many times directly relates to how you are handling things.  Sometimes it is because the disk is slow (aka look at iostat to see your percentages of load due to disk i/o).  Other things is memory and how fast you are swapping processes.

You might want to take a look at adding this: https://github.com/Ocramius/OcraCachedViewResolver

In addition, if you are running a database server on that same machine that further complicates issues and can be due to lookup, missing it from inside of a buffer pool and far more.  Mixed servers are the hardest to configure for that sense as well.  This is where things like cachegrind certainly help when looking at it and gaining a profile of what is happening inside of the actual application.  Many times, the load is simply due to how something was done vs. the framework itself.  There are means for optimizing each step out but without a profile of the application it becomes almost impossible and even improbable to know where you had hit a bottleneck.  This is simply due to the sheer amount of variance that each application has in addition to that there is a vast amount of differences in where people initialize items and more items that several people do when building out their application.

**Comment by faghihian71** [comment]
@tasmaniski @weierophinney  @mwillbanks  after i profiling my application with xdebug and webgrind
i found this high percentage of functions
 Zend\Mvc\View\Http\DefaultRenderingStrategy->render
Zend\EventManager\EventManager->trigger
Zend\EventManager\EventManager->triggerListeners
 Zend\View\Renderer\PhpRenderer->render
end\Mvc\Router\Http\TreeRouteStack->assemble


for doctrine:
Doctrine\ORM\EntityManager->getClassMetadata

and another thing is my routing is with  zf2 hostname routing and in profiling i found out it takes high usage
