### ISSUE TITLE
ZF2 2.5.3 Hydration BC Break

### ISSUE THREAD

**Issue by andrewmackrodt** [zendframework/zf2#7672]
c2300cc updates all components to ^2.5 including zend-mvc which has a BC break regarding hydration, i.e. any methods previously expecting a class in the `Zend\Stdlib\Hydrator` namespace will now receive a class from `Zend\Hydrator`, contrary to the comment in the zend-mvc [pull request](https://github.com/zendframework/zend-mvc/pull/30), this is not backwards compatible.

```
<?php

require __DIR__ . '/vendor/autoload.php';

function zf_get_object_vars(\Zend\Stdlib\Hydrator\HydratorInterface $hydrator, $data) {
    return $hydrator->extract($data);
}

$application = Zend\Mvc\Application::init(['modules' => [], 'module_listener_options' => []]);
$hydratorManager = $application->getServiceManager()->get('HydratorManager');
$hydrator = $hydratorManager->get('ObjectProperty');
$vars = zf_get_object_vars($hydrator, (object) ['abc' => 123]);
var_dump($vars);

// PHP Catchable fatal error: Argument 1 passed to zf_get_object_vars() must be an instance of Zend\Stdlib\Hydrator\HydratorInterface, instance of Zend\Hydrator\ObjectProperty given
```

The documentation for 2.5.3 should be updated to warn users of this breaking change.

**Comment by weierophinney** [comment]
Oof; we indeed made a mistake here in terms of the migration. Since zend-mvc started using the zend-hydrator version of the plugin manager, and zend-stdlib extends that version, there's no way to get the versions from zend-stdlib at this point. I'll work on creating a fix for this shortly.

As a workaround for now, in your application, add:

```json
"require": {
    "zendframework/zendframework": "^2.5",
    "zendframework/zend-mvc": "~2.5.3",
    "zendframework/zend-stdlib": "~2.6.0"
}
```

Then, in one of your `config/autoload/*.global.php` files, alter the 

The latter will ensure that you get a zend-stdlib version from before 2.7, as well as a zend-mvc 2.5 version, ensuring that you'll get the original types.

Once I get a fix in place, we'll do new versions on the zend-stdlib 2.7 and zend-mvc 2.6 repositories that make them backwards compatible, ensuring you get the zend-stdlib types in place. The nice part is that once that's in place, you'll be able to go through your code and update it to use the zend-hydrator interface typehints instead, making the code forwards compatible.

**Comment by weierophinney** [comment]
Updating to zend-mvc 2.6.1 and zend-stdlib 2.7.5 will now restore backwards compatibility.

Once you have, you can start updating your references to Hydrator classes and interfaces to utilize the zend-hydrator versions instead. Since the zend-stdlib interfaces and classes were updated to all inherit from the zend-hydrator counterparts, using the zend-stdlib instances will fulfill the new typehints, while preparing your code for a future update that switches to zend-hydrator for the plugin manager.
