### ISSUE TITLE
Zend/XmlRpc is uncompatible with PHP 7

### ISSUE THREAD

**Issue by ImmRanneft** [zendframework/zf2#7677]
I've found that XmlRpc part of ZF2 isn't compatible with PHP 7 due to class names like "Integer" or "String".

**Comment by samsonasik** [comment]
what version you're using? if you use ~2.4.0, you should have `Zend\XmlRpc\Value\Text` instead.

**Comment by weierophinney** [comment]
@ImmRanneft Have you seen actual issues occur?

I ask, because the test suite runs fine under PHP 7.

Since the class names *as used by the Zend engine* include the namespace, they are fine... so long as you don't attempt to import them. Neither the client nor the server do; they always reference them relative to the namespace.

If you can demonstrate actual, production issues, and detail how to reproduce, we'll look into it, but for now, I have yet to observe any issues.

**Comment by ImmRanneft** [comment]
@samsonasik it was 2.4.9,  found this while inspecting our project and it's dependencies about PHP 7 compatibility.
@weierophinney My fault, guess it was left to have backward compatibility? If so I bag you a pardon for wasting your time. Think we can close an issue.
